create
databese crypto_watcher;

CREATE TABLE USER_INFORMATION
(
    ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL    VARCHAR(255) NOT NULL
);

CREATE TABLE LOGIN_USER
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME       VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(255) NOT NULL,
    EMAIL          VARCHAR(255) NOT NULL,
    USER_ENTITY_ID BIGINT, -- Foreign key sütunu

    CONSTRAINT FK_USER_ENTITY FOREIGN KEY (USER_ENTITY_ID) REFERENCES USER_INFORMATION (ID)
);


CREATE TABLE FAVORITE_COIN
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID        BIGINT      NOT NULL,
    ADDED_AT       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FAVORITE_PRICE DOUBLE      NOT NULL,
    COIN_SYMBOL    VARCHAR(10) NOT NULL,
    COIN_NAME      VARCHAR(50) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER_INFORMATION (ID) ON DELETE CASCADE
);

CREATE TABLE PORTFOLIO
(
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT,
    CONSTRAINT FK_PORTFOLIO_USER FOREIGN KEY (user_id) REFERENCES USER_INFORMATION (id)
);

CREATE TABLE PORTFOLIO_ITEM
(
    id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    portfolio_id   BIGINT,
    crypto_symbol  VARCHAR(255) NOT NULL,
    amount         DOUBLE       NOT NULL,
    purchase_price DOUBLE       NOT NULL,
    purchase_date  DATETIME     NOT NULL,
    CONSTRAINT FK_PORTFOLIO_ITEM_PORTFOLIO FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO (id)
);